name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test,lint]"
      - name: Run tests with pytest
        run: python -m pytest
      - name: check formating with black
        run: black --check --verbose .
      - name: check formating with isort
        run: isort --check-only --diff .
